### ISSUE TITLE
Error compiling M128

### ISSUE THREAD

**Issue by Jan-Ry** [MikeBland/mbtx#1]
Hi,
I'm trying to compile r819 for Atmega128, but having the following error:
![image](https://cloud.githubusercontent.com/assets/13915349/9423214/4586a2c6-48fa-11e5-9b39-a5a7d611139f.png)

Compiles OK for M64.

**Comment by MikeBland** [comment]
Options like "NO_HELI" and not including "FRSKY" were added originally to make the the code fit in the M64, not really to choose what is compiled. With the M128 and M2561, there is enough flash to allow all the code to be included, and they have menu options to enable things like whether the FrSky mod has been done.
The 'correct' command line for the '128 is therefore:
make CPU=128 EXT=FRSKY

**Comment by Jan-Ry** [comment]
Hello Mike,

 

sorry for bugging you again, but I need your help.

I've built (from scratch) a M128 board with Multiprotocol Tx and used the original PD2/PD3 for trim inputs.

And I am unable to compile the code to enable these inputs (I think they are now used for voice module, which I am not planning to use).

Please help.

 

Best Regads,

Jan
