### ISSUE TITLE
Multiprotocol: H8 3D protocol addition

### ISSUE THREAD

**Issue by pascallanger** [MikeBland/mbtx#13]
Hi Mike,
As usual here are the files which need to be updated to add the new H8 3D protocol in er9x and ersky9x:
[er9x_next_H83D_src.zip](https://github.com/MikeBland/mbtx/files/82918/er9x_next_H83D_src.zip)
[ersky9x_next_H83D_src.zip](https://github.com/MikeBland/mbtx/files/82920/ersky9x_next_H83D_src.zip)
Thanks, Pascal

**Comment by MikeBland** [comment]
I'm just committing a release, so this will need to wait until after that. The master branch is now correct for all source files, I merged 'next' to 'master'.

**Comment by pascallanger** [comment]
Forget, I'll change the multi code to hopefully save some flash and H8_3D will be under CG023.
- Pascal
