### ISSUE TITLE
Change reset position of switches?

### ISSUE THREAD

**Issue by M3gaFr3ak** [MikeBland/mbtx#2]
Is there a way to edit the reset position of the switches/pots? I'd like to setup a 3d quadcopter, so the thrttle should be centered on boot. If it isn't changable, how would I need to edit the function checking the throttle idle position? I don't quite understand the "calculation" in that function^^

**Comment by MikeBland** [comment]
er9x or ersky9x?
Both support this:
In the model setup, GENERAL, there is a setting "Thr. Default". This has options of "End" or "Centre".
If you choose "Centre", then the check is for the throttle stick to be at 0%, not -100%.
ersky9x will have a "Custom check" feature available soon. This will allow the checking of a stick or pot to have a specific value.

**Comment by M3gaFr3ak** [comment]
Thanks!
