### ISSUE TITLE
Some USBASP programmers doesn't flash firmware.

### ISSUE THREAD

**Issue by nppc** [MikeBland/mbtx#21]
It's seems, that some versions of USBASP firmware need power cycle of the programmer before each use. But eepe uses USBASP programmer twice while flashing firmware to TX. First time it reads EEPROM, and right after reaiding eeprom, it starts writing... and fails on some USBASP.

So, as a workaround, can you please add a check box that can be unchecked to prevent EEPROM reading prior to flashing firmware?

Thanks a lot.

**Comment by MikeBland** [comment]
This will be in the next release/test version.

**Comment by nppc** [comment]
Oh, thank you Mike! :)

**Comment by MikeBland** [comment]
Test version (for Windows) posted here: http://openrcforums.com/forum/viewtopic.php?f=5&t=4598&p=64969#p64969

**Comment by nppc** [comment]
Ah, thanks! Probably can test it today late evening...
Pavel

2016-05-25 12:49 GMT+02:00 MikeBland <notifications@github.com>:

**Comment by nppc** [comment]
Hi Mike!
I have tested your test version of eepe with eeprom pre-read disabled and
it works now with my usbasp.

Thanks a lot! will close my issue on github.

Pavel

2016-05-25 14:23 GMT+02:00 Pavel Palonen <pavel.palonen@gmail.com>:
