### ISSUE TITLE
cant get the firmwear

### ISSUE THREAD

**Issue by andrewmurphy83** [MikeBland/mbtx#23]
i can not get the firmwear to down load or do i need to download it from github

**Comment by MikeBland** [comment]
From where are are you trying to do the download? The lastest formal release is here: http://www.er9x.com/

**Comment by andrewmurphy83** [comment]
ok i just cant figure it all how to get it to work i just want o make sure how so i dont brick my my tx

**Comment by andrewmurphy83** [comment]
plus it says the something is wrong with the hex and bin files
and i am trying iit from er9x.com i trying to use compaion9x softwear

**Comment by MikeBland** [comment]
You need to use eepe, not companion, to flash firmware.
I suggest you go to http://openrcforums.com/forum/ to ask this question as you will likely get quicker answers, and from others as well as myself.
You need to say what Tx and what programmer you you are using.
