### ISSUE TITLE
FrSky voltage alarm missing in 820?

### ISSUE THREAD

**Issue by larsmm** [MikeBland/mbtx#24]
Hi,
in 808 you could define a voltage threshold for A1/A2 where the frsky module starts to beep on the temeletry pages. I can not find this option in 820. It is a very important function I think. Please help.
Here a screenshot of 808: http://file.emiter.hu/Modellezes/FrSky/Oszto/Oszto%20028.jpg
Lars

**Comment by MikeBland** [comment]
You may get er9x itself to provide an alarm, so I removed the code to set alarms on the module. Many users don't use a FrSky module, so the code space is more useful for other features.
Eepe includes a facility to read and set the alarms on the module if you need them.
You may find the Er9x manual, found here: http://openrcforums.com/forum/viewtopic.php?f=5&t=6473&sid=29ce3b5e82aa0696679decc44392e163, a useful reference for setting up a "Voice Alarm". While called "Voice", it is also possible to generate audio tones using the stock buzzer from them.
