### ISSUE TITLE
Feature Request: Customizable channel quantity in protocol selection

### ISSUE THREAD

**Issue by cjmarzano** [MikeBland/mbtx#25]
I have a feature request related to the new Orange Rx FrSky Dongle from HobbyKing.

https://hobbyking.com/en_us/frsky-protocol-usb-wireless-dongle-for-simulatior.html

I'm able to bind my 9xr Pro w/ XJT module to the dongle successfully on r220 via the XJT protocol, D8, 8 channel. However, the connection is intermittent. I believe the issue was identified by HelpMeFPV such that the USB dongle will reset if more than 6 channels are used. ~1:10 in this video https://www.youtube.com/watch?v=BjNJBWlEZ10. It'd be great if we could force a nonstandard number of channels to make this work.

**Comment by MikeBland** [comment]
I've just checked the openTx code for using less than 8 channels in D8 mode with a XJT. All it does is set the unused channels to their centre position. The PXX protocol requires that 8 channels are sent to the XJT, even when you select less than 8 channels.
The same effect should therefore occur if you ensure the unused channels (7 and 8) have nothing in the mixer and there is no sub-trim (offset in the limits menu). On the main display where the channel outputs are displayed as numbers, check that channels 7 and 8 show as 0.0.

**Comment by cjmarzano** [comment]
Latest XJT firmware build 161214 (the non-LBT version) with r220, proto XJT, D8, 8 channel, appears to be working for me after a rebind. Thanks for the help Mike, closing this.
