### ISSUE TITLE
broken wiki..? 

### ISSUE THREAD

**Issue by davidbuzz** [MikeBland/mbtx#26]
http://openrcforums.com/wiki/index.php/Er9x_user_guide  ( and every page in the wiki ) 
throws a bunch of php errors: 
Strict Standards: Declaration of Auth_phpBB::modifyUITemplate() should be compatible with AuthPlugin::modifyUITemplate(&$template, &$type) in /var/www/html/openrcforums.com/wiki/extensions/Auth_phpBB.php on line 81

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

Warning: preg_match_all(): Compilation failed: group name must start with a non-digit at offset 4 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 876

Warning: Invalid argument supplied for foreach() in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 877

Warning: preg_replace(): Compilation failed: group name must start with a non-digit at offset 4 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 881

Warning: preg_match_all(): Compilation failed: group name must start with a non-digit at offset 4 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 876

Warning: Invalid argument supplied for foreach() in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 877

Warning: preg_replace(): Compilation failed: group name must start with a non-digit at offset 4 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 881

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /var/www/html/openrcforums.com/wiki/includes/MagicWord.php on line 902

**Comment by MikeBland** [comment]
I've already alerted the site manager, I can't do anything myself.
