### ISSUE TITLE
Reversing gimbals in controls menu is not functioning.

### ISSUE THREAD

**Issue by laegion420** [MikeBland/mbtx#27]
I updated to the latest er9x firmware and I have taranis gimbals installed...The gimbal reversing feature no longer seems to function I can select it but it will not scroll through options.

**Comment by MikeBland** [comment]
It is protected like the hardware menu, so just power on holding the left horizontal trim to the left to enable editing of the reversing feature.

**Comment by laegion420** [comment]
Thank you! I got it working.
