### ISSUE TITLE
er9x-m128 do not have "frsky mod done" menu

### ISSUE THREAD

**Issue by jacklee00** [MikeBland/mbtx#31]
hello, my transmitter is flysky th-9x, i  have the Frsky mod,reroute the pin2 to pin41 and pin3 to pin42, pin2 and pin3 used for the telemetry. then change the chip to atmega128.
then, i flash the er9x-Frsky with eePe , i can see the telemetry with DJT module work well, and i can check the RSSI and TSSI and etc is correct . so i think it is not the hardware problem. 
then i flash the er9x-m128 with eePe,  there is no 'Frsky mod done' in  radio setup ---general menu, 
Ail and Thr switch is always ON and the frsky telemetry is not work either.
I have tried the er9x-m128 from the er9x.com. it not not work.
I want to use the Frsky telemetry , any help is welcome.

**Comment by MikeBland** [comment]
The setting is in the "Hardware" menu. Enable this menu by holding the left trime switch to the left at power on. The hardware menu will then appear in the "Radio Setup" menu list.

**Comment by jacklee00** [comment]
@MikeBland   THANKS  a lot . I will have a try.
