### ISSUE TITLE
Multi protocol: LBT/EU frskyX Subprotocols missing in ersky9x

### ISSUE THREAD

**Issue by meg4max1** [MikeBland/mbtx#32]
on my 9XR Pro, the subprotocols EU_8 and EU_16  are missing in the frskyx protocol of the multimodule

**Comment by meg4max1** [comment]
To me and my poor coding skills it appears to be there in the er9x code and missing in the ersky9x code.

**Comment by MikeBland** [comment]
Which revision of the firmware?
Do you have the file "multi.txt" in the root directory of your SD card?

**Comment by meg4max1** [comment]
I have 
V.1760-Mike
date: 04.12.2016
time: 10:18:39
svn: ersky9x-r220
mod: revb-x

i do not have the file in my sdcard/root. Do i need it?

**Comment by MikeBland** [comment]
The firmware has a default set of names for the Multi protocol, but as other protocols and sub-rotocols are added, these are not included. The firmware looks for the file "multi.txt", which contains the the "latest" protocol and sub-protocol names, so putting the file in the root of the SD card should get the missing sub-protocols to appear.
