### ISSUE TITLE
no frsky telemetry data with multi protocol sub openlrs

### ISSUE THREAD

**Issue by jacklee00** [MikeBland/mbtx#37]
I have openlrs and 128m rc with er9x with r822a,frsky mode with no inversion added,when i use ppm mode,i can see telemtry data like rssi and A1 A2,when i change to multi protocol openlrs ,i can bind and working well ,the only problem is no telemtry back,i have tried the test version with openlrs fix,no good
i want to know where go wrong,the er9x or the openlrsng bug,or a invernter is needed,?if it fixed, can you offer a firmware,
 thank you for any help

**Comment by mikeller** [comment]
@jacklee00: Check the telemetry settings for telemetry type (FrSky), and Com port (1), and Com Port invert (try all settings). These settings are overridden when changing the Protocol, so they might have changed on you.

**Comment by MikeBland** [comment]
What is the Multi-protocol module you are using for openLrs?
When running the Multi-protocol, any telemetry data is expected to be received at 100000 baud.
Is the telemetry in FrSky hub format? If not, what format is it in?

@mikeller He has er9x not ersky9x so the Com port and inversion do not apply.

**Comment by mikeller** [comment]
@MikeBland:

> What is the Multi-protocol module you are using for openLrs?

There is no multiprotocol module that does openLRSng (which is 433 MHz). But the normal openLRSng hardware supports the Multiprotocol protocol: https://github.com/openLRSng/openLRSng/releases/tag/3.9.0-rc2

> When running the Multi-protocol, any telemetry data is expected to be received at 100000 baud.

The openLRSng hardware does that - has to, since it has only 1 UART to share between RX and TX.

> Is the telemetry in FrSky hub format? If not, what format is it in?

It's in FrSky format. @jacklee00: I forgot to mention above, you'll have to configure the RX to send telemetry as FrSky (**not** SmartPort).

**Comment by jacklee00** [comment]
sorry for my delay replay, 
@mikeller i configure the TX in FrSky format, when binding ,the Rx should be Frsky format, too.
I tried ,but the Frsky telemetry not work,either.It is really wired. 
Any way ,the PPM protocol work well, and i can get rssi a1 a2  in the way.
thank you all for your good project.

**Comment by mikeller** [comment]
@jacklee00: Happy to have helped. I started working on injecting Multiprotocol telemetry into the 'normal' telemetry data, but it's not finished yet - I think this should help with getting er9x to recognise the telemetry when Multiprotocol is used.
