### ISSUE TITLE
Update to QT 5

### ISSUE THREAD

**Issue by Jellono** [MikeBland/mbtx#4]
Update Code base for use in Qt5.X on EEPE and EEPSkye.
This is the first pass at this and we need to re visit the stamp-eepe.h and  stamp-eepskye.h files.

**Comment by MikeBland** [comment]
I just added:
#include <QMessageBox>
#include <QScrollBar>
to avroutputdialog.cpp and it compiles on Qt4 with no problem, so I think the Qt5 changes will be backward compatible, including the toLatin1 change.

The stamp files are created when I do a command line build for a release.

**Comment by Jellono** [comment]
Can you let me know what the command line for release compilation looks like?

**Comment by Defrenne** [comment]
seems that installing eepe on linux mint 18 is not straitforward where to start is it a make file somwhere.

**Comment by MikeBland** [comment]
At present the build of eepe (and eepskye) is 32 bit.
Is your Linux installation 64 bit? If so, then you need the 32-bit support libraries.
