### ISSUE TITLE
erskyTx r222 issue

### ISSUE THREAD

**Issue by dadantsou** [MikeBland/mbtx#45]
Hi Mike!

There was an issue with the latest test version of erskyTx r222 published on 29-May-2019 23:03 linked [here](https://openrcforums.com/forum/download/file.php?id=18484)

While trying to edit mix on any of the model on my 9XR PRO, the radio reboot instantly without the splash screen but playing the welcome voice. Also the selected model become the first one.

This issue doen't appear on the version appeared on 27-May-2019 23:36, that I tested.

Hope I help you!

And thanks for your great work!

**Comment by MikeBland** [comment]
It is working OK for me. Please confirm you flashed ersky9xr_rom.bin (check the 'r'), and the version shows:
DATE: 29.05.2019
TIME: 22.00.58
MOD: REVB-X

Mike

**Comment by dadantsou** [comment]
Hi Mike!

The issue is only present when I flashed the radio through the bootloader menu. It doesn't seem present when flashing though eepskye. Try different times but the issue is always present when flashing through the radio bootloader, and I verified that I flashed the right firmware (ersky9xr_rom.bin date : 29.05.2019, time : 22:00:58, MOD : REVB-X)

**Comment by dadantsou** [comment]
Hi Mike!

Found out the problem.

I've never update my bootloader since v1.7. So I think there is a problem when flashing with old bootloader, 'cause when I updated my bootloader and then reflash my 9XR PRO, the issue wasn't anymore there.

Cheers!
