### ISSUE TITLE
unnable to change splash screen on "er9x for M64-FrSky" v821 or 822

### ISSUE THREAD

**Issue by mbalun** [MikeBland/mbtx#49]
Hello Mike, 
In eepe (latest from er9x.com) the splash screen editor works for all version of er9x except for the m64-FrSky (normal and serial voice) ones (both latest stable and test version) 
![2020-05-15 08_03_12-eePe - EEPROM Editor](https://user-images.githubusercontent.com/8628587/82017073-9cdf0d80-9682-11ea-98d3-e57f29cc62db.png)

Is there a possibility to add this to the eepe editor?

**Comment by MikeBland** [comment]
The splash image uses 1024 bytes of flash memory. On the M64, we need all the flash memory we can get, so I reduced the image to half the resolution so it only uses 256 bytes of flash memory, and just a few extra bytes to expand it back to "full size".
This means the standard customise splash doesn't work. I'll need to sort using a "half size" image (64x32) to get this to work.
I decided more features were more useful than having a custom splash display!

Mike

**Comment by mbalun** [comment]
I supposed there was a real valid reason behind it. I would be happy editing even the half size one. you know how it is, everybody wants to have a small unique tuch to it. 

I really apreciate the work you have done. althtrought I didnt wrotre at all untill now, I read almost all of the development threads on forums you were participating in.

Do yoo think you can add an editor to eepe for this version or it will be kept uneditable ?

**Comment by MikeBland** [comment]
I think I have it working. I hope to post a test version of eepe tomorrow.
You will just need to create a 64x32 image, load it into eepe and save it to the .hex file.

Mike

**Comment by mbalun** [comment]
Thank you very much Mike.

**Comment by MikeBland** [comment]
Test version of eepe posted here: https://openrcforums.com/forum/viewtopic.php?f=5&t=4598&p=64969#p64969
Backup your existing eepe.exe and copy this one to your eepe directory.

Mike

**Comment by mbalun** [comment]
Working perfectly on 822c version :) I also noticed that the hex size got 154kB instead of 179kB of original image. so far I dont see any error in the operation of the firmware.  

![helicopter-drawing-22](https://user-images.githubusercontent.com/8628587/82141988-63043780-9839-11ea-9e55-5385a4a6f2ae.png)
this is the image I used :)

Thank you very much for your effort :)
