### ISSUE TITLE
er9x radio with FRSKY does not fit into standard atmega64

### ISSUE THREAD

**Issue by kgawda** [MikeBland/mbtx#50]
I tried compiling er9x for Turnigy 9x with telemetry modification (compatible with FrSky). The resulting binary is too large for ATMega64 memory.

Steps to reproduce (on clean Ubuntu 18.04 or 20.04):
```bash
apt update
apt-get install -y gcc-avr avr-libc gcc avrdude build-essential ruby git
git clone https://github.com/MikeBland/mbtx
cd mbtx/radio/er9x/src/
make EXT=FRSKY HELI=NO
```
The result says: `Program:   68120 bytes (103.9% Full)`

I tried with different options and the lowest size came with:
```bash
make EXT=FRSKY HELI=NO TEMPLATES=NO NOPOTSCROLL=YES V2=YES
```

This is still above possible size: `Program:   65986 bytes (100.7% Full)`

**Comment by MikeBland** [comment]
I compile on windows and I have had to stay at V4.8.0 of the compiler as later versions create larger compiled code that doesn't fit in the M64.

Mike

**Comment by kgawda** [comment]
ok, I checked this as a workaround: it fits when running the same steps on Ubuntu 14.04 (via Docker)
