### ISSUE TITLE
afhds2a telemetry not read correct value every frame so we get 0 on telemetry screen and I hear alarm

### ISSUE THREAD

**Issue by macem** [MikeBland/mbtx#53]
I have turnigy 9xr pro with ersky9x r223 and frsky QX7 with erx9d-r222 and the same problem with telemetry in afhds 2a receivers fs-ia6B. This is only happened when I change model in tx and will connect with model. For RSSI and ExV i get for second frame no values, so on screen with telemetry I see zeros and my alarm all time turn on. But when I change model in tx and turn off tx and then turn on tx and will connect with model everything work fine.

**Comment by MikeBland** [comment]
I assume this is with a multiprotocol module?
Does the problem occur if you have two models on the Tx, both already bound, and you then change models?

**Comment by macem** [comment]
Hi Mike yes with TX multimodule with new firmware, yes I have two models in Tx, and are bound. I turn on transmitter where I have selected one model, then I select second model and bind with telemetry and this problem exists. As a workaround after select second model I need to turn of Tx and turn on again.

**Comment by MikeBland** [comment]
Does the problem only occur if you do a bind after changing models, but works OK if you just change models without binding?

**Comment by macem** [comment]
Hi the problem occur without banding, sorry I corrected my comments before.

**Comment by macem** [comment]
I upgraded to new firmware and it is working, so please close, seems before there was other r223 firmware with AFHDS2a debug
