### ISSUE TITLE
Script problem

### ISSUE THREAD

**Issue by dadantsou** [MikeBland/mbtx#54]
Hi Mike. There is a problem with **erskyTx 224** on **9XR Pro**. When I launch any script, the radio always reboot.

Thanks

**Comment by MikeBland** [comment]
I've fixed the problem, it was a memory sizing problem specific to the 'PRO when running BASIC scripts (small LUA scripts that fit ran OK), all other radios appear to be OK!
I've updated the file on er9x.com, it now reports the revision as 224a.
